import { FeedPost, FeedUser } from './types';

const USERS: FeedUser[] = [
  { id: 'u1', name: 'Valeria Solís', handle: 'val_style', avatarUrl: 'https://i.pravatar.cc/150?u=val' },
  { id: 'u2', name: 'Camila Ruiz', handle: 'cami.looks', avatarUrl: 'https://i.pravatar.cc/150?u=cami' },
  { id: 'u3', name: 'Sofía Torres', handle: 'sofi.moda', avatarUrl: 'https://i.pravatar.cc/150?u=sofia' },
  { id: 'u4', name: 'Isabella Morales', handle: 'isa.fashion', avatarUrl: 'https://i.pravatar.cc/150?u=isa' },
  { id: 'u5', name: 'Renata Pérez', handle: 'renata.looks', avatarUrl: 'https://i.pravatar.cc/150?u=renata' },
];

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 'f1',
    user: USERS[0],
    imageUrl: 'https://loremflickr.com/400/700/fashion,outfit?lock=101',
    caption: 'Outfit del día ✨ Blazer oversize + mom jeans + loafers',
    likes: 234,
    comments: 18,
    saves: 45,
    timestamp: 'hace 2 h',
    isLiked: false,
    isSaved: false,
    isOwn: false,
    categories: ['casual'],
  },
  {
    id: 'f2',
    user: USERS[1],
    imageUrl: 'https://loremflickr.com/400/700/fashion,black?lock=102',
    caption: 'Monocromático total 🖤 todo negro, todo poder',
    likes: 512,
    comments: 34,
    saves: 98,
    timestamp: 'hace 5 h',
    isLiked: true,
    isSaved: false,
    isOwn: false,
    categories: ['formal'],
  },
  {
    id: 'f3',
    user: USERS[2],
    imageUrl: 'https://loremflickr.com/400/700/fashion,dress?lock=103',
    caption: 'Romantic vibes 🌸 vestido midi + botas altas',
    likes: 187,
    comments: 12,
    saves: 67,
    timestamp: 'hace 8 h',
    isLiked: false,
    isSaved: true,
    isOwn: false,
    categories: ['romantic'],
  },
  {
    id: 'f4',
    user: USERS[3],
    imageUrl: 'https://loremflickr.com/400/700/streetstyle?lock=104',
    caption: 'Street style desde Santiago 🇨🇱',
    likes: 423,
    comments: 29,
    saves: 112,
    timestamp: 'hace 1 d',
    isLiked: false,
    isSaved: false,
    isOwn: false,
    categories: ['street'],
  },
  {
    id: 'f5',
    user: USERS[4],
    imageUrl: 'https://loremflickr.com/400/700/fashion,minimal?lock=105',
    caption: 'Minimalismo chic 🤍 menos es más',
    likes: 305,
    comments: 21,
    saves: 88,
    timestamp: 'hace 1 d',
    isLiked: true,
    isSaved: true,
    isOwn: false,
    categories: ['minimalist'],
  },
  {
    id: 'f6',
    user: USERS[0],
    imageUrl: 'https://loremflickr.com/400/700/fashion,autumn?lock=106',
    caption: 'Cores para el otoño 🍂 marrón + terracota',
    likes: 276,
    comments: 16,
    saves: 73,
    timestamp: 'hace 2 d',
    isLiked: false,
    isSaved: false,
    isOwn: false,
  },
  {
    id: 'f7',
    user: USERS[1],
    imageUrl: 'https://loremflickr.com/400/700/fashion,suit?lock=107',
    caption: 'Power suit moment 💼 traje sastre a rayas',
    likes: 641,
    comments: 47,
    saves: 134,
    timestamp: 'hace 3 d',
    isLiked: false,
    isSaved: false,
    isOwn: false,
  },
  {
    id: 'f8',
    user: USERS[2],
    imageUrl: 'https://loremflickr.com/400/700/fashion,neutral?lock=108',
    caption: 'Beige palette 🤎 el neutro perfecto para el día',
    likes: 198,
    comments: 9,
    saves: 55,
    timestamp: 'hace 4 d',
    isLiked: false,
    isSaved: false,
    isOwn: false,
  },
];

export const MOCK_SAVED_POSTS: FeedPost[] = MOCK_FEED_POSTS.filter(p => p.isSaved);