import { FeedPost, FeedUser } from './types';

const USERS: FeedUser[] = [
  { id: 'u1', name: 'Valeria Solís',   handle: 'val_style',     avatarUrl: 'https://i.pravatar.cc/150?u=val' },
  { id: 'u2', name: 'Camila Ruiz',     handle: 'cami.looks',    avatarUrl: 'https://i.pravatar.cc/150?u=cami' },
  { id: 'u3', name: 'Sofía Torres',    handle: 'sofi.moda',     avatarUrl: 'https://i.pravatar.cc/150?u=sofia' },
  { id: 'u4', name: 'Isabella Morales',handle: 'isa.fashion',   avatarUrl: 'https://i.pravatar.cc/150?u=isa' },
  { id: 'u5', name: 'Renata Pérez',    handle: 'renata.looks',  avatarUrl: 'https://i.pravatar.cc/150?u=renata' },
];

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: 'f1',
    user: USERS[0],
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600',
    caption: 'Outfit del día ✨ Blazer oversize + mom jeans + loafers',
    likes: 234, comments: 18, saves: 45,
    timestamp: 'hace 2 h',
    isLiked: false, isSaved: false, isOwn: false,
    categories: ['casual'],
    colors: ['neutral', 'earth'],
    aiPrompt: 'Estilo Casual Chic de Día. Líneas limpias con silueta relajada. Predominan los neutros cálidos con un toque estructurado en el blazer oversize.',
    clothingItems: ['Blazer oversize beige', 'Mom jeans de tiro alto', 'Loafers de cuero'],
    accessories: ['Bolso de cuero pequeño', 'Cinturón delgado'],
  },
  {
    id: 'f2',
    user: USERS[1],
    imageUrl: 'https://images.unsplash.com/photo-1492288991661-058aa541ff43?auto=format&fit=crop&q=80&w=600',
    caption: 'Monocromático total 🖤 todo negro, todo poder',
    likes: 512, comments: 34, saves: 98,
    timestamp: 'hace 5 h',
    isLiked: true, isSaved: false, isOwn: false,
    categories: ['formal'],
    colors: ['dark'],
    aiPrompt: 'Estilo Power Dressing Monocromático. Toda la paleta en negro transmite autoridad y sofisticación urbana. El corte estructurado eleva el conjunto al nivel editorial.',
    clothingItems: ['Blazer negro estructurado', 'Pantalón negro de tiro alto', 'Top negro sin mangas'],
    accessories: ['Botas de cuero negro', 'Maxi aretes dorados'],
  },
  {
    id: 'f3',
    user: USERS[2],
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=600',
    caption: 'Romantic vibes 🌸 vestido midi + botas altas',
    likes: 187, comments: 12, saves: 67,
    timestamp: 'hace 8 h',
    isLiked: false, isSaved: true, isOwn: false,
    categories: ['romantic'],
    colors: ['pink', 'neutral'],
    aiPrompt: 'Estilo Romántico Moderno. La combinación del vestido floral con botas de cuero crea un balance perfecto entre feminidad y carácter urbano.',
    clothingItems: ['Vestido midi floral con mangas abullonadas', 'Botas altas de cuero marrón'],
    accessories: ['Collar de perlas', 'Mini bolso de mano'],
  },
  {
    id: 'f4',
    user: USERS[3],
    imageUrl: 'https://images.unsplash.com/photo-1434389678219-e08b8cb10620?auto=format&fit=crop&q=80&w=600',
    caption: 'Street style desde Santiago 🇨🇱',
    likes: 423, comments: 29, saves: 112,
    timestamp: 'hace 1 d',
    isLiked: false, isSaved: false, isOwn: false,
    categories: ['street'],
    colors: ['blue', 'dark'],
    aiPrompt: 'Estilo Streetwear Latinoamericano. Mezcla audaz de prendas urbanas con detalles locales. La paleta fría refuerza la estética callejera cosmopolita.',
    clothingItems: ['Sudadera gráfica oversize', 'Cargo pants azul marino', 'Sneakers chunky blancos'],
    accessories: ['Gorra con visera', 'Mochila negra'],
  },
  {
    id: 'f5',
    user: USERS[4],
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=600',
    caption: 'Minimalismo chic 🤍 menos es más',
    likes: 305, comments: 21, saves: 88,
    timestamp: 'hace 1 d',
    isLiked: true, isSaved: true, isOwn: false,
    categories: ['minimalist'],
    colors: ['neutral'],
    aiPrompt: 'Estilo Minimalista Escandinavo. Paleta absolutamente neutra en blanco roto y crema. Cada pieza es funcional y la silueta habla por sí sola sin adornos innecesarios.',
    clothingItems: ['Trench coat crema de corte recto', 'Pantalón de lino blanco hueso', 'Camiseta básica de algodón'],
    accessories: ['Bolso tote de tela natural', 'Sandalias planas minimalistas'],
  },
  {
    id: 'f6',
    user: USERS[0],
    imageUrl: 'https://images.unsplash.com/photo-1550639525-c97d455acf70?auto=format&fit=crop&q=80&w=600',
    caption: 'Cores para el otoño 🍂 marrón + terracota',
    likes: 276, comments: 16, saves: 73,
    timestamp: 'hace 2 d',
    isLiked: false, isSaved: false, isOwn: false,
    categories: ['autumn'],
    colors: ['earth', 'neutral'],
    aiPrompt: 'Estilo Otoñal Tonal. La paleta tierra —terracota, camel y marrón— crea una armonía perfecta con el entorno natural. Look ideal para transición de estación.',
    clothingItems: ['Suéter de punto terracota', 'Pantalón de pana camel', 'Botines de ante marrón'],
    accessories: ['Bufanda de lana a cuadros', 'Bolso estructurado camel'],
  },
  {
    id: 'f7',
    user: USERS[1],
    imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=600',
    caption: 'Power suit moment 💼 traje sastre a rayas',
    likes: 641, comments: 47, saves: 134,
    timestamp: 'hace 3 d',
    isLiked: false, isSaved: false, isOwn: false,
    categories: ['formal'],
    colors: ['dark', 'neutral'],
    aiPrompt: 'Estilo Business Power Feminino. El traje a rayas chalk proyecta confianza y liderazgo. La proporción del blazer largo equilibra perfectamente las proporciones corporales.',
    clothingItems: ['Blazer largo a rayas chalk', 'Pantalón a juego de tiro alto', 'Blusa de seda blanca'],
    accessories: ['Pumps de tacón bajo', 'Maletín de cuero negro'],
  },
  {
    id: 'f8',
    user: USERS[2],
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=600',
    caption: 'Beige palette 🤎 el neutro perfecto para el día',
    likes: 198, comments: 9, saves: 55,
    timestamp: 'hace 4 d',
    isLiked: false, isSaved: false, isOwn: false,
    categories: ['casual'],
    colors: ['neutral', 'earth'],
    aiPrompt: 'Estilo Soft Neutral. La gama beige head-to-toe transmite calma y elegancia sin esfuerzo. Un look que demuestra que los neutros, bien ejecutados, son el pináculo del estilo.',
    clothingItems: ['Conjunto de punto beige (top + pantalón)', 'Chaleco de punto texturado'],
    accessories: ['Sandalias planas en tono nude', 'Bolso de paja natural'],
  },
];

export const MOCK_SAVED_POSTS: FeedPost[] = MOCK_FEED_POSTS.filter(p => p.isSaved);

export const MOCK_OWN_POSTS: FeedPost[] = [
  {
    id: 'own1',
    user: { id: 'me', name: 'Tú', handle: 'mi_estilo', avatarUrl: 'https://i.pravatar.cc/150?u=me' },
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600',
    caption: 'Probando combinaciones nuevas con GORYUZ 🤖👗',
    likes: 45, comments: 3, saves: 12,
    timestamp: 'hace 2 d',
    isLiked: false, isSaved: false, isOwn: true,
    categories: ['casual'],
    colors: ['neutral'],
  },
  {
    id: 'own2',
    user: { id: 'me', name: 'Tú', handle: 'mi_estilo', avatarUrl: 'https://i.pravatar.cc/150?u=me' },
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=600',
    caption: 'Outfit para la oficina de hoy 💼✨',
    likes: 67, comments: 5, saves: 20,
    timestamp: 'hace 1 sem',
    isLiked: false, isSaved: false, isOwn: true,
    categories: ['formal'],
    colors: ['dark', 'neutral'],
  },
  {
    id: 'own3',
    user: { id: 'me', name: 'Tú', handle: 'mi_estilo', avatarUrl: 'https://i.pravatar.cc/150?u=me' },
    imageUrl: 'https://images.unsplash.com/photo-1434389678219-e08b8cb10620?auto=format&fit=crop&q=80&w=600',
    caption: 'El look de los viernes 🎉',
    likes: 31, comments: 1, saves: 8,
    timestamp: 'hace 2 sem',
    isLiked: false, isSaved: false, isOwn: true,
    categories: ['casual'],
    colors: ['blue'],
  },
];
